# Generated by Django 3.1.5 on 2022-05-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0007_auto_20220527_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='customer',
        ),
    ]
