# Generated by Django 3.1.5 on 2022-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0008_remove_booked_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
