# Generated by Django 3.1.5 on 2022-05-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0009_product_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
