# Generated by Django 3.1.5 on 2022-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0010_product_vendor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
