# Generated by Django 3.1.5 on 2022-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0011_product_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
