# Generated by Django 3.1.5 on 2022-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0012_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flight_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
