# Generated by Django 3.1.5 on 2022-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0013_product_flight_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drone_range',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
