# Generated by Django 3.1.5 on 2022-05-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jai_Kisan', '0014_product_drone_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flight_time',
            field=models.IntegerField(default='1'),
        ),
    ]
